<a href="https://colab.research.google.com/github/kritika1234567/python-tutorial1/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(45)

45


In [ ]:
print('Hello,world!')

Hello,world!


In [ ]:
myint=1
print(myint)

1


In [ ]:
myfloat=8.76
print(myfloat)
hiy=3.77
print(hiy)
mystring="kritika"
print(mystring)


8.76
3.77
kritika


In [ ]:
one=1
two=2
three=one+two
print(three)
print("hello"+"world")

3
helloworld


In [ ]:
s=4
if s==9:
    print("yes")
else:
    print("no")


no


In [ ]:
mystring = "hello"
myfloat = 10.0
myint = 20

# testing code
if mystring == "hello":
    print("String: %s" % mystring)
if isinstance(myfloat, float) and myfloat == 10.0:
    print("Float: %f" % myfloat)
if isinstance(myint, int) and myint == 20:
    print("Integer: %d" % myint)

String: hello
Float: 10.000000
Integer: 20


In [ ]:
mylist = []
mylist.append(1)
mylist.append(2)
mylist.append(3)
print(mylist[0]) 
print(mylist[1]) 
print(mylist[2]) 
for x in mylist:
    print(x)

1
2
3
1
2
3


In [ ]:
list_1=[2,3,4,5,6,]
print(list_1[4])

6


In [ ]:
even_numbers = [2,4,6,8]
odd_numbers = [1,3,5,7]
all_numbers = odd_numbers + even_numbers
print(all_numbers)

[1, 3, 5, 7, 2, 4, 6, 8]


In [ ]:
nicework="nice"+" "+"work"
print(nicework)

nice work


In [ ]:
print([4,5,6,7,8]*4)

[4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8]


In [ ]:
name = "kitty"
print("Hello, %s!" % name)

Hello, kitty!


In [ ]:
name = "John"
age = 23
print("%s is %d years old." % (name, age))

John is 23 years old.


In [ ]:
data = ("John", "Doe", 53.44)
format_string = "Hello %s %s. Your current balance is $%s."

print(format_string % data)

Hello John Doe. Your current balance is $53.44.


In [ ]:
astring = "Hello world!"
print("single quotes are ' '")

print(len(astring))
print(astring.count("l"))
print(astring.index("o"))
print(astring[3:7])
print(astring[3:7:2])
print(astring[3:7:1])
print(astring[::-1])
print(astring.upper())
print(astring.lower())
print(astring.startswith("Hello"))
print(astring.endswith("asdfasdfasdf"))
afewwords = astring.split(" ")


single quotes are ' '
12
3
4
lo w
l 
lo w
!dlrow olleH
HELLO WORLD!
hello world!
True
False


In [ ]:
x = 2
if x == 3:
    print("x equals two!")
else:
    print("x does not equal to two.")

x does not equal to two.


In [ ]:
x = [1,2,3]
y = [1,2,3]
print(x == y) # Prints out True
print(x is y) # Prints out False

True
False


In [ ]:
number = 16
second_number = 0
first_array = [1,2,3]
second_array = [1,2]

if number > 15:
    print("1")

if first_array:
    print("2")

if len(second_array) == 2:
    print("3")

if len(first_array) + len(second_array) == 5:
    print("4")


1
2
3
4


In [ ]:
primes = [2, 3, 5, 7]
for prime in primes:
    print(prime)

2
3
5
7


In [ ]:
for x in range(5):
    print(x)

# Prints out 3,4,5
for x in range(3, 6):
    print(x)

# Prints out 3,5,7
for x in range(3, 8, 2):
    print(x)

0
1
2
3
4
3
4
5
3
5
7


In [ ]:
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4


In [ ]:
for x in range(10):
    if x % 2 == 0:
        continue
    print(x)

1
3
5
7
9


In [ ]:
count=0
while(count<5):
    print(count)
    count +=1
else:
    print("count value reached %d" %(count))

# Prints out 1,2,3,4
for i in range(1, 10):
    if(i%5==0):
        break
    print(i)
else:
    print("this is not printed because for loop is terminated because of break but not due to fail in condition")

0
1
2
3
4
count value reached 5
1
2
3
4


In [ ]:
def my_function():
    print("Hello From My Function!")

In [ ]:
def my_function(x):
  return 5 * x

print(my_function(3))
print(my_function(5))
print(my_function(9))

15
25
45


In [ ]:
def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

Emil Refsnes
Tobias Refsnes
Linus Refsnes


In [ ]:
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")


The youngest child is Linus


In [ ]:
def my_function(country = "Norway"):
  print("I am from " + country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

I am from Sweden
I am from India
I am from Norway
I am from Brazil


In [ ]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)


apple
banana
cherry


In [ ]:
import numpy as np
a=np.array([1,2,3])
a
a[0]


1

In [ ]:
import numpy as np
import time
import sys

l=range(1000)
print(sys.getsizeof(5)*len(l))

array=np.arange(1000)
print(array.size*array.itemsize)

28000
8000


In [ ]:
import numpy as np
import time
import sys
size=10000000

l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)
#python list 
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("python list took:" , (time.time()-start)*1000)
#numpy arrays
start=time.time()
result=a1+a2
print("numpy took:",(time.time()-start)*1000)

python list took: 1286.7786884307861
numpy took: 170.9463596343994


In [ ]:
import numpy as np
a1=np.array([1,2,3,4,])
a2=np.array([5,6,7,8,])
a1+a2
a1-a2
a1*a2
a1/a2
a1%a2



array([1, 2, 3, 4])

In [ ]:
import numpy as np
a=np.array([1,2,3,])
a.itemsize

8

In [ ]:
import numpy as np
a=np.array([1,2,3,])
a.dtype

dtype('int64')

In [ ]:

import numpy as np
a=np.array([(1,2),(3,4),(5,6)],dtype=np.float64)
a.itemsize
a.dtype

dtype('float64')

In [ ]:
import numpy as np
a=np.array([(1,2),(3,4),(5,6)],dtype=np.float64)
print(a.size)
print(a.shape)
a=np.array([(1,2),(3,4),(5,6)],dtype=np.complex)
a

6
(3, 2)


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
import numpy as np
np.zeros((4,5))
np.ones((2,3))
np.arange(1,5)
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
import numpy as np
a=np.array([(1,2),(3,4),(5,6)])
a.shape
a.reshape(2,3)
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
a=np.array([(1,2),(3,4),(5,6)])
a.min()
a.max()
a.sum()
a.sum(axis=0)
a.sum(axis=1)
np.sqrt(a)
np.std(a)

1.707825127659933